// Generated by gencpp from file turtlecontrol/circle_service.msg
// DO NOT EDIT!


#ifndef TURTLECONTROL_MESSAGE_CIRCLE_SERVICE_H
#define TURTLECONTROL_MESSAGE_CIRCLE_SERVICE_H

#include <ros/service_traits.h>


#include <circle_serviceRequest.h>
#include <circle_serviceResponse.h>


namespace turtlecontrol
{

struct circle_service
{

typedef circle_serviceRequest Request;
typedef circle_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct circle_service
} // namespace turtlecontrol


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlecontrol::circle_service > {
  static const char* value()
  {
    return "fc3db95a57294e8a3ce4451857513454";
  }

  static const char* value(const ::turtlecontrol::circle_service&) { return value(); }
};

template<>
struct DataType< ::turtlecontrol::circle_service > {
  static const char* value()
  {
    return "turtlecontrol/circle_service";
  }

  static const char* value(const ::turtlecontrol::circle_service&) { return value(); }
};


// service_traits::MD5Sum< ::turtlecontrol::circle_serviceRequest> should match
// service_traits::MD5Sum< ::turtlecontrol::circle_service >
template<>
struct MD5Sum< ::turtlecontrol::circle_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlecontrol::circle_service >::value();
  }
  static const char* value(const ::turtlecontrol::circle_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlecontrol::circle_serviceRequest> should match
// service_traits::DataType< ::turtlecontrol::circle_service >
template<>
struct DataType< ::turtlecontrol::circle_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::turtlecontrol::circle_service >::value();
  }
  static const char* value(const ::turtlecontrol::circle_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlecontrol::circle_serviceResponse> should match
// service_traits::MD5Sum< ::turtlecontrol::circle_service >
template<>
struct MD5Sum< ::turtlecontrol::circle_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlecontrol::circle_service >::value();
  }
  static const char* value(const ::turtlecontrol::circle_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlecontrol::circle_serviceResponse> should match
// service_traits::DataType< ::turtlecontrol::circle_service >
template<>
struct DataType< ::turtlecontrol::circle_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::turtlecontrol::circle_service >::value();
  }
  static const char* value(const ::turtlecontrol::circle_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLECONTROL_MESSAGE_CIRCLE_SERVICE_H
