// Generated by gencpp from file turtlecontrol/circle_serviceResponse.msg
// DO NOT EDIT!


#ifndef TURTLECONTROL_MESSAGE_CIRCLE_SERVICERESPONSE_H
#define TURTLECONTROL_MESSAGE_CIRCLE_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlecontrol
{
template <class ContainerAllocator>
struct circle_serviceResponse_
{
  typedef circle_serviceResponse_<ContainerAllocator> Type;

  circle_serviceResponse_()
    {
    }
  circle_serviceResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct circle_serviceResponse_

typedef ::turtlecontrol::circle_serviceResponse_<std::allocator<void> > circle_serviceResponse;

typedef boost::shared_ptr< ::turtlecontrol::circle_serviceResponse > circle_serviceResponsePtr;
typedef boost::shared_ptr< ::turtlecontrol::circle_serviceResponse const> circle_serviceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace turtlecontrol

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::turtlecontrol::circle_serviceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlecontrol/circle_serviceResponse";
  }

  static const char* value(const ::turtlecontrol::circle_serviceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::turtlecontrol::circle_serviceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct circle_serviceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlecontrol::circle_serviceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::turtlecontrol::circle_serviceResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TURTLECONTROL_MESSAGE_CIRCLE_SERVICERESPONSE_H
