// Generated by gencpp from file chatter/newmsgRequest.msg
// DO NOT EDIT!


#ifndef CHATTER_MESSAGE_NEWMSGREQUEST_H
#define CHATTER_MESSAGE_NEWMSGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chatter
{
template <class ContainerAllocator>
struct newmsgRequest_
{
  typedef newmsgRequest_<ContainerAllocator> Type;

  newmsgRequest_()
    : msg()  {
    }
  newmsgRequest_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _msg_type;
  _msg_type msg;





  typedef boost::shared_ptr< ::chatter::newmsgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chatter::newmsgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct newmsgRequest_

typedef ::chatter::newmsgRequest_<std::allocator<void> > newmsgRequest;

typedef boost::shared_ptr< ::chatter::newmsgRequest > newmsgRequestPtr;
typedef boost::shared_ptr< ::chatter::newmsgRequest const> newmsgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chatter::newmsgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chatter::newmsgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chatter::newmsgRequest_<ContainerAllocator1> & lhs, const ::chatter::newmsgRequest_<ContainerAllocator2> & rhs)
{
  return lhs.msg == rhs.msg;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chatter::newmsgRequest_<ContainerAllocator1> & lhs, const ::chatter::newmsgRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chatter

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::chatter::newmsgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chatter::newmsgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatter::newmsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chatter::newmsgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatter::newmsgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chatter::newmsgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chatter::newmsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d96ed730776804754140b85e64c862e";
  }

  static const char* value(const ::chatter::newmsgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d96ed7307768047ULL;
  static const uint64_t static_value2 = 0x54140b85e64c862eULL;
};

template<class ContainerAllocator>
struct DataType< ::chatter::newmsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chatter/newmsgRequest";
  }

  static const char* value(const ::chatter::newmsgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chatter::newmsgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string msg\n"
"\n"
;
  }

  static const char* value(const ::chatter::newmsgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chatter::newmsgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct newmsgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chatter::newmsgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chatter::newmsgRequest_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHATTER_MESSAGE_NEWMSGREQUEST_H
